name: deploy the nodejs application using GHCR in Github Actions

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/harikrishna2525/my-nodejs-app:latest .

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/harikrishna2525/my-nodejs-app:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Make sure this matches your EC2 instance region

      - name: Deploy to EC2 using AWS CLI SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Node.js App from GitHub Actions" \
            --parameters '{"commands":["echo \"${{ secrets.GHCR_PAT }}\" | docker login ghcr.io -u harikrishna2525 --password-stdin","docker pull ghcr.io/harikrishna2525/my-nodejs-app:latest","docker stop my-nodejs-app || true","docker rm my-nodejs-app || true","docker run -d --name my-nodejs-app -p 3000:3000 ghcr.io/harikrishna2525/my-nodejs-app:latest"]}'
