name : Deploy the nextjs app to Ec2 using Github Actions 

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Build the Docker image using GHCR
        run: docker build -t ghcr.io/harikrish2525/my-nextjs-app:${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push the Docker image to GHCR
        run: docker push ghcr.io/harikrish2525/my-nextjs-app:${{ github.sha }}


 deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your actual AWS region

      # Step 2: Send the deployment script to EC2 via AWS SSM Run Command
      - name: Deploy to EC2 via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Next.js App" \
            --parameters 'commands=[
              "export CR_PAT=${{ secrets.GHCR_PAT }}",
              "echo $CR_PAT | docker login ghcr.io -u harikrish2525 --password-stdin",
              "docker pull ghcr.io/harikrish2525/my-nextjs-app:${{ github.sha }}",
              "docker stop my-nextjs-app || true",
              "docker rm my-nextjs-app || true",
              "docker run -d --name my-nextjs-app -p 3000:3000 ghcr.io/harikrish2525/my-nextjs-app:${{ github.sha }}"
            ]' \
            --query "Command.CommandId" \
            --output text

